### ISSUE TITLE
Problem with final output

### ISSUE THREAD

**Issue by shitalmali** [pranab/sifarish#10]
Hello Pranab,
I am getting number in front of user id in final output , can you help me to know how is the final output of recommendation.Here recommendation is about movies.i have given my data as a input which is having movie name instead of item ID and person name instead of user ID. but I didn't understand from where that no came. and recommendation gets repeated with different numbers.
sample output:
1bhushan,3idiots,245
1bhushan,dilchahatahai,558
1bhushan,sarfarosh,463
1bhushan,satya,515
1bhushan,sholay,479
1krishna,3idiots,188
1krishna,dilchahatahai,248
1krishna,sarfarosh,415
1krishna,satya,216
1krishna,sholay,319
1neha,3idiots,234
1neha,dilchahatahai,404
1neha,sarfarosh,379
1neha,satya,378
1neha,sholay,407
1poonam,3idiots,186
1poonam,dilchahatahai,464
1poonam,sarfarosh,357
1poonam,satya,359
1poonam,sholay,433
bhushan,dilchahatahai,355
bhushan,sarfarosh,232
bhushan,satya,243
bhushan,sholay,364
2shubham,dilchahatahai,301
2shubham,sarfarosh,197
2shubham,satya,206
2shubham,sholay,309
3sayali,dilchahatahai,74
3sayali,sarfarosh,48
3sayali,satya,51
3sayali,sholay,76
3shubham,3idiots,120
3shubham,dilchahatahai,136
3shubham,sarfarosh,164
3shubham,satya,255

**Comment by pranab** [comment]
Step 7 in the tutorial produces the output from the core MR workflow of collaborative filtering. Please send me sample output of step 7.  After 7 all MR jobs are optional. Which ones did you execute after step 7.
The output is (userID, itemID, predictedRating). The predictedRating is a score indicating to what extend the user will like the item. For each user, typically you sort them by descending order of predictedRating and pick the top k.

**Comment by shitalmali** [comment]
This is the output of 7 th step only.

**Comment by shitalmali** [comment]
OK,I am getting output ( user-ID, item-ID, predictedRating ) in this format. and I will arrange that in descending order .But don't understand why it repeated with different number added before user-ID

2shubham,dilchahatahai,301
2shubham,sarfarosh,197
2shubham,satya,206
2shubham,sholay,309
3sayali,dilchahatahai,74
3shubham,3idiots,120
3shubham,dilchahatahai,136
3shubham,sarfarosh,164
3shubham,satya,255

like this for each user?
