### ISSUE TITLE
Exception : Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentials

### ISSUE THREAD

**Issue by shitalmali** [pranab/sifarish#7]
Hello pranab,
I got "Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/auth/AWSCredentials " this exception while running ImplicitRatingEstimator to generate Implicit rating.
Plz help. and why we required AWSCredentials ?? I didn't find this in your project.

**Comment by pranab** [comment]
Are you running in AWS EMR and using S3 for configuration property file. If so, you need have amazon client lib jar in class path at run time. All the config stuff is in the project chombo, which sifarish depends on.

**Comment by pranab** [comment]
Replied in github

Pranab

http://www.linkedin.com/in/pkghosh 
http://pkghosh.wordpress.com
 



Date: Wed, 8 Apr 2015 02:06:24 -0700

**Comment by shitalmali** [comment]
No i am running it on standalone mode machine. Not using AWS EMR. I have also added Chombo jar using libjar.

**Comment by pranab** [comment]
Please send me your script or command line for running the job. Somehow, it's trying to read
the properties configuration file from S3

Pranab

http://www.linkedin.com/in/pkghosh 
http://pkghosh.wordpress.com
 



Date: Wed, 8 Apr 2015 21:38:02 -0700

**Comment by shitalmali** [comment]
Hello pranab,
Thanks for your reply. The problem get solved. It's asking for AWS jars
because of chombo dependencies in chombo class.
